/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MovementTypeObjectPageObjectPage journey");

        opaTest("Navigate to MovementTypeObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheMovementTypeListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheMovementTypeListGenerated.onTable().iCheckRows();
            When.onTheMovementTypeListGenerated.onTable().iPressRow(0);

            Then.onTheMovementTypeObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheMovementTypeObjectPageGenerated.iCheckSection({ section: "FieldGroup::Main" });
            Then.onTheMovementTypeObjectPageGenerated.onForm({ section: "FieldGroup::Main" }).iCheckField({ property: "description" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});